request to merge assignment 9 into develop branch
munendra-successive/Js-training pull request #8
Opened 2023-10-25 09:02 UTC by munendra-successive

1.create repo and add Readme.md file

2.Install the lodash package using npm install lodash. and use any of its function

3.create a new folder named 'math' and create a file math.js. In math.js, define two functions:
a. add(a, b): takes two numbers as arguments and returns their sum.
b. subtract(a, b): takes two numbers as arguments and returns their difference.
create a new file index.js and just export those functions and then use those function in any of the file

2023-10-25 12:21 UTC, UrvashiChaudhary requested changes

2023-10-25 12:21 UTC, UrvashiChaudhary commented on assignment-9/index.js
> +a. add(a, b): takes two numbers as arguments and returns their sum.
Expected: create index.js file within math folder and export the functions from there. Then use it any of the file.

2023-10-25 12:21 UTC, UrvashiChaudhary commented on assignment-9/package.json
> +    "lodash": "^4.17.21"
Please remove carat(^) symbol

2023-10-25 12:30 UTC, munendra-successive commented on assignment-9/index.js
> +a. add(a, b): takes two numbers as arguments and returns their sum.
Created index.js in math folder

2023-10-25 12:31 UTC, munendra-successive commented on assignment-9/package.json
> +    "lodash": "^4.17.21"
carat symbol removed

2023-10-26 06:04 UTC, UrvashiChaudhary approved these changes

2023-10-26 06:05 UTC, merged